{{- if and .Values.saml.enabled (not .Values.saml.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tikti.fullname" . }}-saml
  labels:
    {{- include "tikti.labels" . | nindent 4 }}
type: Opaque
stringData:
  sp.key: |
{{ .Values.saml.sp.key | indent 4 }}
  sp.crt: |
{{ .Values.saml.sp.crt | indent 4 }}
{{- end }}
