{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tikti.fullname" . }}-secrets
  labels:
{{ include "tikti.labels" . | indent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  apiKey: {{ .Values.secrets.apiKey | b64enc | quote }}
  redisPassword: {{ .Values.secrets.redisPassword | b64enc | quote }}
  jwksPrivateKey: {{ .Values.secrets.jwksPrivateKey | b64enc | quote }}
  samlSpPrivateKey: {{ .Values.secrets.samlSpPrivateKey | b64enc | quote }}
  samlSpCertificate: {{ .Values.secrets.samlSpCertificate | b64enc | quote }}
{{- end }}
