{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tikti.serviceAccountName" . }}
  labels:
{{ include "tikti.labels" . | indent 4 }}
{{- end }}
